
export const routes = {
  auth: "/auth",
  driverApply: "/driver-apply",

  user: {
    root: "/user",
    catalog: "/user/catalog",
    product: (id: string) => `/user/product/${id}`,
    cart: "/user/cart",
    checkout: "/user/checkout",
    orders: "/user/orders",
    order: (id: string) => `/user/orders/${id}`,
    activeProcurements: "/user/active-procurements",
    procurement: (id: string) => `/user/procurements/${id}`,
    payment: "/user/payment",
    profile: "/user/profile",
    profileEdit: "/user/profile/edit",
    disputes: "/user/disputes",
    dispute: (id: string) => `/user/disputes/${id}`,
    disputeCreate: (orderId: string) => `/user/disputes/new?orderId=${orderId}`,
    notifications: "/user/notifications",
    support: "/user/support",
    addresses: "/user/addresses",
    /** @deprecated используйте addresses — посёлок доставки */
    pickupPoints: "/user/addresses",
  },

  driver: {
    root: "/driver",
    procurements: "/driver/procurements",
    route: "/driver/route",
    handout: "/driver/handout",
    map: "/driver/map",
    profile: "/driver/profile",
    profileEdit: "/driver/profile/edit",
    disputes: "/driver/disputes",
    dispute: (id: string) => `/driver/disputes/${id}`,
    notifications: "/driver/notifications",
    support: "/driver/support",
  },

  admin: {
    root: "/admin",
    users: "/admin/users",
    orders: "/admin/orders",
    products: "/admin/products",
    procurements: "/admin/procurements",
    drivers: "/admin/drivers",
    driver: (id: string) => `/admin/drivers/${id}`,
    settlements: "/admin/settlements",
    analytics: "/admin/analytics",
    driverApplications: "/admin/driver-applications",
    tickets: "/admin/tickets",
    ticket: (id: string) => `/admin/tickets/${id}`,
    profile: "/admin/profile",
  },
} as const
