
export const routes = {
  auth: "/auth",

  home: "/",
  catalog: "/catalog",
  product: (id: string) => `/product/${id}`,
  cart: "/cart",
  checkout: "/checkout",
  orders: "/orders",
  order: (id: string) => `/orders/${id}`,
  activeProcurements: "/active-procurements",
  procurement: (id: string) => `/procurements/${id}`,
  profile: "/profile",
  profileEdit: "/profile/edit",
  notifications: "/notifications",
  disputes: "/disputes",
  disputeCreate: (orderId: string) => `/disputes/new?orderId=${orderId}`,
  payment: "/payment",
  support: "/support",
  addresses: "/addresses",
  pickupPoints: "/pickup-points",

  driver: {
    root: "/driver",
    procurements: "/driver/procurements",
    route: "/driver/route",
    orders: "/driver/orders",
    map: "/driver/map",
    profile: "/driver/profile",
  },

  driverApply: "/driver-apply",

  employee: {
    root: "/employee",
    intake: "/employee/intake",
    handout: "/employee/handout",
    procurements: "/employee/procurements",
    orders: "/employee/handout",
    scan: "/employee/scan",
    profile: "/employee/profile",
  },

  admin: {
    root: "/admin",
    users: "/admin/users",
    orders: "/admin/orders",
    products: "/admin/products",
    routes: "/admin/routes",
    procurements: "/admin/procurements",
    drivers: "/admin/drivers",
    settlements: "/admin/settlements",
    analytics: "/admin/analytics",
    driverApplications: "/admin/driver-applications",
    pvz: "/admin/pvz",
    pvzEmployees: "/admin/pvz-employees",
    tickets: "/admin/tickets",
    profile: "/admin/profile",
  },
} as const
