server {
    listen 80;
    server_name coopykt.ru www.coopykt.ru;
    return 301 https://coopykt.ru$request_uri;
}

server {
    listen 443 ssl http2;
    server_name coopykt.ru;

    ssl_certificate /etc/letsencrypt/live/coopykt.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coopykt.ru/privkey.pem;

    client_max_body_size 25M;

    root /var/www/coopykt;
    index index.html;

    include /opt/diplom/deploy/nginx-locations.inc;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl http2;
    server_name www.coopykt.ru;

    ssl_certificate /etc/letsencrypt/live/coopykt.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coopykt.ru/privkey.pem;

    return 301 https://coopykt.ru$request_uri;
}
