server {
    listen 80;
    server_name coopykt.ru www.coopykt.ru;

    client_max_body_size 25M;

    root /var/www/coopykt;
    index index.html;

    include /opt/diplom/deploy/nginx-locations.inc;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
